server:
  port: 9001
spring:
  application:
    name: tensquare-base
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base?useUnicode=true&characterEncoding=utf8
    username: root
    password: haoxi123
  jpa:
    database: mysql
    show-sql: true

